spring.datasource.url=jdbc:mysql://localhost:3306/otobus_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=14i18o21101L*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true